# 02 Data Prep

In [1]:
# common imports
import requests
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import sys
from datetime import datetime

sys.executable

'/opt/anaconda3/bin/python'

In [2]:
# will display all the columns in the df now
pd.set_option('display.max_columns', 500)

In [3]:
sys.path

['/Users/mirror/Desktop/GitHub/NFL_Game_Predictor',
 '/opt/anaconda3/lib/python38.zip',
 '/opt/anaconda3/lib/python3.8',
 '/opt/anaconda3/lib/python3.8/lib-dynload',
 '',
 '/Users/mirror/.local/lib/python3.8/site-packages',
 '/opt/anaconda3/lib/python3.8/site-packages',
 '/opt/anaconda3/lib/python3.8/site-packages/aeosa',
 '/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions',
 '/Users/mirror/.ipython']

In [4]:
# Importing data from csv file
# avoid using hard coded paths like the next two lines
# path = "/Users/mirror/Desktop/GitHub/nfl_game_predictor/data/scraped_data.csv"
# df = pd.read_csv(path) # instead, use this

from src.config import DATA_DIR
path = DATA_DIR / 'scraped_data.csv'
df = pd.read_csv(path)

df.head(30)

,season,team,week,day,date,time,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts
0,2022,MIA,1,Sun,September 11,1:00PM ET,W,NaN,1-0,NaN,New England Patriots,20.0,7.0,18.0,307.0,242.0,65.0,NaN,17.0,271.0,193.0,78.0,3.0,6.08,8.28,1.98
1,2022,MIA,2,Sun,September 18,1:00PM ET,W,NaN,2-0,@,Baltimore Ravens,42.0,38.0,27.0,547.0,461.0,86.0,2.0,23.0,473.0,318.0,155.0,NaN,32.00,-20.31,-7.09
2,2022,MIA,3,Sun,September 25,1:00PM ET,W,NaN,3-0,NaN,Buffalo Bills,21.0,19.0,15.0,212.0,171.0,41.0,NaN,31.0,497.0,382.0,115.0,1.0,7.45,-15.88,4.86
3,2022,MIA,4,Thu,September 29,8:15PM ET,L,NaN,3-1,@,Cincinnati Bengals,15.0,27.0,20.0,378.0,293.0,85.0,2.0,16.0,371.0,304.0,67.0,NaN,0.48,-9.11,-3.73
4,2022,MIA,5,Sun,October 9,1:00PM ET,L,NaN,3-2,@,New York Jets,17.0,40.0,19.0,295.0,158.0,137.0,2.0,21.0,322.0,187.0,135.0,NaN,-6.15,-11.86,-3.66
5,2022,MIA,6,Sun,October 16,1:00PM ET,L,NaN,3-3,NaN,Minnesota Vikings,16.0,24.0,23.0,458.0,385.0,73.0,3.0,11.0,234.0,156.0,78.0,NaN,-8.38,4.43,-4.75
6,2022,MIA,7,Sun,October 23,8:20PM ET,W,NaN,4-3,NaN,Pittsburgh Steelers,16.0,10.0,17.0,372.0,261.0,111.0,NaN,19.0,341.0,246.0,95.0,3.0,0.04,6.72,-2.49
7,2022,MIA,8,Sun,October 30,1:00PM ET,W,NaN,5-3,@,Detroit Lions,31.0,27.0,27.0,476.0,369.0,107.0,1.0,22.0,393.0,311.0,82.0,NaN,25.47,-19.14,-0.59
8,2022,MIA,9,Sun,November 6,1:00PM ET,W,NaN,6-3,@,Chicago Bears,35.0,32.0,21.0,379.0,302.0,77.0,NaN,23.0,368.0,116.0,252.0,NaN,19.83,-17.18,2.01
9,2022,MIA,10,Sun,November 13,1:00PM ET,W,NaN,7-3,NaN,Cleveland Browns,39.0,17.0,29.0,491.0,296.0,195.0,NaN,20.0,297.0,185.0,112.0,1.0,28.50,1.04,-4.93
10,2022,BUF,1,Thu,September 8,8:20PM ET,W,NaN,1-0,@,Los Angeles Rams,31.0,10.0,23.0,413.0,292.0,121.0,4.0,19.0,243.0,191.0,52.0,3.0,13.89,10.29,-3.96
11,2022,BUF,2,Mon,September 19,7:15PM ET,W,NaN,2-0,NaN,Tennessee Titans,41.0,7.0,23.0,414.0,313.0,101.0,NaN,12.0,187.0,107.0,80.0,4.0,17.69,18.01,1.55
12,2022,BUF,3,Sun,September 25,1:00PM ET,L,NaN,2-1,@,Miami Dolphins,19.0,21.0,31.0,497.0,382.0,115.0,1.0,15.0,212.0,171.0,41.0,NaN,15.88,-7.45,-4.86
13,2022,BUF,4,Sun,October 2,1:00PM ET,W,NaN,3-1,@,Baltimore Ravens,23.0,20.0,22.0,326.0,201.0,125.0,2.0,22.0,296.0,134.0,162.0,2.0,2.10,2.66,-1.69
14,2022,BUF,5,Sun,October 9,1:00PM ET,W,NaN,4-1,NaN,Pittsburgh Steelers,38.0,3.0,21.0,552.0,432.0,120.0,2.0,23.0,364.0,310.0,54.0,2.0,20.66,9.42,3.54
15,2022,BUF,6,Sun,October 16,4:25PM ET,W,NaN,5-1,@,Kansas City Chiefs,24.0,20.0,26.0,443.0,318.0,125.0,1.0,23.0,387.0,319.0,68.0,2.0,11.13,-6.45,0.56
16,2022,BUF,8,Sun,October 30,8:20PM ET,W,NaN,6-1,NaN,Green Bay Packers,27.0,17.0,20.0,369.0,216.0,153.0,2.0,21.0,398.0,190.0,208.0,1.0,12.79,-5.55,4.01
17,2022,BUF,9,Sun,November 6,1:00PM ET,L,NaN,6-2,@,New York Jets,17.0,20.0,19.0,317.0,183.0,134.0,2.0,21.0,310.0,136.0,174.0,1.0,0.54,-7.64,2.11
18,2022,BUF,10,Sun,November 13,1:00PM ET,L,OT,6-3,NaN,Minnesota Vikings,30.0,33.0,29.0,486.0,311.0,175.0,4.0,24.0,481.0,334.0,147.0,2.0,1.45,-4.80,-0.39
19,2022,BUF,11,Sun,November 20,1:00PM ET,W,NaN,7-3,NaN,Cleveland Browns,31.0,23.0,22.0,357.0,186.0,171.0,NaN,27.0,396.0,316.0,80.0,1.0,6.00,-10.86,13.72
20,2022,NE,1,Sun,September 11,1:00PM ET,L,NaN,0-1,@,Miami Dolphins,7.0,20.0,17.0,271.0,193.0,78.0,3.0,18.0,307.0,242.0,65.0,NaN,-8.28,-6.08,-1.98
21,2022,NE,2,Sun,September 18,1:00PM ET,W,NaN,1-1,@,Pittsburgh Steelers,17.0,14.0,18.0,376.0,252.0,124.0,1.0,16.0,243.0,152.0,91.0,2.0,6.14,3.44,-3.25
22,2022,NE,3,Sun,September 25,1:00PM ET,L,NaN,1-2,NaN,Baltimore Ravens,26.0,37.0,22.0,447.0,302.0,145.0,4.0,19.0,394.0,206.0,188.0,2.0,3.50,-11.67,-3.18
23,2022,NE,4,Sun,October 2,4:25PM ET,L,OT,1-3,@,Green Bay Packers,24.0,27.0,17.0,271.0,104.0,167.0,1.0,24.0,443.0,244.0,199.0,2.0,-2.00,-5.17,2.64
24,2022,NE,5,Sun,October 9,1:00PM ET,W,NaN,2-3,NaN,Detroit Lions,29.0,0.0,22.0,364.0,188.0,176.0,1.0,17.0,312.0,211.0,101.0,2.0,10.08,22.04,-3.38
25,2022,NE,6,Sun,October 16,1:00PM ET,W,NaN,3-3,@,Cleveland Browns,38.0,15.0,20.0,399.0,301.0,98.0,1.0,16.0,328.0,258.0,70.0,4.0,11.30,12.35,-0.09
26,2022,NE,7,Mon,October 24,8:15PM ET,L,NaN,3-4,NaN,Chicago Bears,14.0,33.0,12.0,260.0,190.0,70.0,4.0,24.0,390.0,147.0,243.0,1.0,-10.97,-8.77,-0.11
27,2022,NE,8,Sun,October 30,1:00PM ET,W,NaN,4-4,@,New York Jets,22.0,17.0,19.0,288.0,161.0,127.0,1.0,17.0,387.0,336.0,51.0,3.0,-9.31,2.30,12.01
28,2022,NE,9,Sun,November 6,1:00PM ET,W,NaN,5-4,NaN,Indianapolis Colts,26.0,3.0,11.0,203.0,133.0,70.0,1.0,8.0,121.0,43.0,78.0,1.0,-9.55,31.93,-1.05
29,2022,NE,11,Sun,November 20,1:00PM ET,W,NaN,6-4,NaN,New York Jets,10.0,3.0,13.0,297.0,198.0,99.0,NaN,6.0,103.0,44.0,59.0,NaN,-9.78,18.64,-5.40

### Quick Exploration

In [5]:
df.shape

(15080, 26)

In [6]:
df.dtypes

season                 int64
team                  object
week                  object
day                   object
date                  object
time                  object
result                object
ot                    object
record                object
@                     object
opp                   object
points_scored        float64
points_allowed       float64
1st_downs            float64
totyd                float64
passyd               float64
rushyd               float64
to                   float64
1st_downs_allowed    float64
totyd_allowed        float64
passyd_allowed       float64
rushyd_allowed       float64
to_forced            float64
off_exp_pts          float64
def_exp_pts          float64
sts_exp_pts          float64
dtype: object

In [7]:
df.isnull().sum()

season                   0
team                     0
week                     0
day                      0
date                     0
time                     0
result                   0
ot                   14150
record                   0
@                     7512
opp                      0
points_scored            0
points_allowed           0
1st_downs                0
totyd                    0
passyd                   2
rushyd                   0
to                    3315
1st_downs_allowed        0
totyd_allowed            0
passyd_allowed           2
rushyd_allowed           0
to_forced             3315
off_exp_pts              0
def_exp_pts              0
sts_exp_pts              0
dtype: int64

In [8]:
df['ot'].isnull().sum()

14150

In [9]:
# discovering how many times an opponent played a game
df.opp.value_counts()

New England Patriots        508
Green Bay Packers           501
Pittsburgh Steelers         495
Indianapolis Colts          492
Philadelphia Eagles         489
Seattle Seahawks            487
San Francisco 49ers         486
Denver Broncos              482
Kansas City Chiefs          481
Minnesota Vikings           480
New Orleans Saints          479
Dallas Cowboys              479
Atlanta Falcons             478
New York Giants             476
Tampa Bay Buccaneers        476
New York Jets               473
Miami Dolphins              472
Arizona Cardinals           472
Chicago Bears               471
Buffalo Bills               471
Cincinnati Bengals          470
Detroit Lions               466
Carolina Panthers           461
Jacksonville Jaguars        457
Baltimore Ravens            454
Washington Redskins         423
Cleveland Browns            416
Oakland Raiders             408
Tennessee Titans            397
San Diego Chargers          382
St. Louis Rams              346
Houston Texans              341
Los Angeles Rams            133
Los Angeles Chargers         93
Houston Oilers               48
Las Vegas Raiders            44
Washington Football Team     34
Tennessee Oilers             32
Los Angeles Raiders          16
Washington Commanders        11
Name: opp, dtype: int64

In [10]:
# # importing a new library that was recommended to me by my mentor
# import sweetviz as sv

# df_report = sv.analyze(df)
# df_report.show_html()
# #df_report.show_notebook()

In [11]:
# compares two dataframes via sweetviz
#df_comp = sv.compare(df)

In [12]:
# another way to get great insights is to use the comparison functionality to split your dataset into 2 sub-populations.
#df_comp_intra = sv.compare_intra(df)

### Initial Data Cleansing

In [13]:
# there are only supposed to be 32 teams in the NFL. some teams have changed their name and/or location.
len(df.opp.unique())

40

In [14]:
# some teams have changed their name and/or location, which created another opponent.
# manually replacing team names.
df.loc[df["opp"] == "Washington Redskins", "opp"] = "Washington Commanders"
df.loc[df["opp"] == "Washington Football Team", "opp"] = "Washington Commanders"
df.loc[df["opp"] == "Oakland Raiders", "opp"] = "Las Vegas Raiders"
df.loc[df["opp"] == "Los Angeles Raiders", "opp"] = "Las Vegas Raiders"
df.loc[df["opp"] == "Houston Oilers", "opp"] = "Tennessee Titans"
df.loc[df["opp"] == "Tennessee Oilers", "opp"] = "Tennessee Titans"
df.loc[df["opp"] == "San Diego Chargers", "opp"] = "Los Angeles Chargers"
df.loc[df["opp"] == "St. Louis Rams", "opp"] = "Los Angeles Rams"

In [15]:
# verifying that there are only 32 teams in the df.opp column now.
len(df.opp.unique())

32

In [16]:
# first sort the df by season and week
df = df.sort_values(by=['season', 'week'], ascending=[False, True])

In [17]:
# right now, we two records for each game played because we scraped the data for each team's season
# we need to reduce the df to only have one record for each game played
df.head(33)

,season,team,week,day,date,time,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts
0,2022,MIA,1,Sun,September 11,1:00PM ET,W,NaN,1-0,NaN,New England Patriots,20.0,7.0,18.0,307.0,242.0,65.0,NaN,17.0,271.0,193.0,78.0,3.0,6.08,8.28,1.98
10,2022,BUF,1,Thu,September 8,8:20PM ET,W,NaN,1-0,@,Los Angeles Rams,31.0,10.0,23.0,413.0,292.0,121.0,4.0,19.0,243.0,191.0,52.0,3.0,13.89,10.29,-3.96
20,2022,NE,1,Sun,September 11,1:00PM ET,L,NaN,0-1,@,Miami Dolphins,7.0,20.0,17.0,271.0,193.0,78.0,3.0,18.0,307.0,242.0,65.0,NaN,-8.28,-6.08,-1.98
30,2022,NYJ,1,Sun,September 11,1:00PM ET,L,NaN,0-1,NaN,Baltimore Ravens,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0,-8.07,-3.65,-5.04
40,2022,BAL,1,Sun,September 11,1:00PM ET,W,NaN,1-0,@,New York Jets,24.0,9.0,13.0,274.0,211.0,63.0,1.0,24.0,380.0,297.0,83.0,2.0,3.65,8.07,5.04
50,2022,CIN,1,Sun,September 11,1:00PM ET,L,OT,0-1,NaN,Pittsburgh Steelers,20.0,23.0,32.0,432.0,299.0,133.0,5.0,13.0,267.0,192.0,75.0,NaN,-7.49,8.41,-4.85
60,2022,CLE,1,Sun,September 11,1:00PM ET,W,NaN,1-0,@,Carolina Panthers,26.0,24.0,23.0,355.0,138.0,217.0,NaN,15.0,261.0,207.0,54.0,1.0,6.82,-5.38,1.66
70,2022,PIT,1,Sun,September 11,1:00PM ET,W,OT,1-0,@,Cincinnati Bengals,23.0,20.0,13.0,267.0,192.0,75.0,NaN,32.0,432.0,299.0,133.0,5.0,-8.41,7.49,4.85
80,2022,TEN,1,Sun,September 11,4:25PM ET,L,NaN,0-1,NaN,New York Giants,20.0,21.0,19.0,359.0,266.0,93.0,1.0,19.0,394.0,156.0,238.0,2.0,5.97,-3.72,-2.44
90,2022,IND,1,Sun,September 11,1:00PM ET,T,OT,0-0-1,@,Houston Texans,20.0,20.0,33.0,517.0,340.0,177.0,2.0,20.0,299.0,222.0,77.0,1.0,5.67,2.14,-9.43
101,2022,JAX,1,Sun,September 11,1:00PM ET,L,NaN,0-1,@,Washington Commanders,22.0,28.0,24.0,383.0,260.0,123.0,1.0,26.0,390.0,305.0,85.0,3.0,3.64,-9.54,-0.26
111,2022,HOU,1,Sun,September 11,1:00PM ET,T,OT,0-0-1,NaN,Indianapolis Colts,20.0,20.0,20.0,299.0,222.0,77.0,1.0,33.0,517.0,340.0,177.0,2.0,-2.14,-5.67,9.43
121,2022,KC,1,Sun,September 11,4:25PM ET,W,NaN,1-0,@,Arizona Cardinals,44.0,21.0,33.0,488.0,360.0,128.0,1.0,18.0,282.0,179.0,103.0,NaN,33.41,-2.29,-6.88
131,2022,LAC,1,Sun,September 11,4:25PM ET,W,NaN,1-0,NaN,Las Vegas Raiders,24.0,19.0,18.0,355.0,279.0,76.0,NaN,18.0,320.0,256.0,64.0,3.0,6.30,2.73,-1.95
141,2022,LV,1,Sun,September 11,4:25PM ET,L,NaN,0-1,@,Los Angeles Chargers,19.0,24.0,18.0,320.0,256.0,64.0,3.0,18.0,355.0,279.0,76.0,NaN,-2.73,-6.30,1.95
151,2022,DEN,1,Mon,September 12,8:20PM ET,L,NaN,0-1,@,Seattle Seahawks,16.0,17.0,20.0,433.0,330.0,103.0,2.0,19.0,253.0,177.0,76.0,1.0,9.94,-4.10,-6.84
161,2022,PHI,1,Sun,September 11,1:00PM ET,W,NaN,1-0,@,Detroit Lions,38.0,35.0,27.0,455.0,239.0,216.0,NaN,23.0,386.0,205.0,181.0,1.0,21.15,-15.67,-0.78
171,2022,DAL,1,Sun,September 11,8:20PM ET,L,NaN,0-1,NaN,Tampa Bay Buccaneers,3.0,19.0,12.0,244.0,173.0,71.0,1.0,18.0,347.0,195.0,152.0,1.0,-19.40,-0.55,2.24
181,2022,NYG,1,Sun,September 11,4:25PM ET,W,NaN,1-0,@,Tennessee Titans,21.0,20.0,19.0,394.0,156.0,238.0,2.0,19.0,359.0,266.0,93.0,1.0,3.72,-5.97,2.44
191,2022,WAS,1,Sun,September 11,1:00PM ET,W,NaN,1-0,NaN,Jacksonville Jaguars,28.0,22.0,26.0,390.0,305.0,85.0,3.0,24.0,383.0,260.0,123.0,1.0,9.54,-3.64,0.26
202,2022,MIN,1,Sun,September 11,4:25PM ET,W,NaN,1-0,NaN,Green Bay Packers,23.0,7.0,19.0,395.0,269.0,126.0,NaN,21.0,338.0,227.0,111.0,2.0,9.99,1.89,1.12
212,2022,DET,1,Sun,September 11,1:00PM ET,L,NaN,0-1,NaN,Philadelphia Eagles,35.0,38.0,23.0,386.0,205.0,181.0,1.0,27.0,455.0,239.0,216.0,NaN,15.67,-21.15,0.78
222,2022,GB,1,Sun,September 11,4:25PM ET,L,NaN,0-1,@,Minnesota Vikings,7.0,23.0,21.0,338.0,227.0,111.0,2.0,19.0,395.0,269.0,126.0,NaN,-1.89,-9.99,-1.12
233,2022,CHI,1,Sun,September 11,1:00PM ET,W,NaN,1-0,NaN,San Francisco 49ers,19.0,10.0,15.0,204.0,105.0,99.0,1.0,17.0,331.0,155.0,176.0,2.0,0.67,11.26,-0.42
244,2022,TB,1,Sun,September 11,8:20PM ET,W,NaN,1-0,@,Dallas Cowboys,19.0,3.0,18.0,347.0,195.0,152.0,1.0,12.0,244.0,173.0,71.0,1.0,0.55,19.40,-2.24
254,2022,ATL,1,Sun,September 11,1:00PM ET,L,NaN,0-1,NaN,New Orleans Saints,26.0,27.0,26.0,416.0,215.0,201.0,2.0,18.0,385.0,234.0,151.0,1.0,7.50,-4.62,0.51
265,2022,NO,1,Sun,September 11,1:00PM ET,W,NaN,1-0,@,Atlanta Falcons,27.0,26.0,18.0,385.0,234.0,151.0,1.0,26.0,416.0,215.0,201.0,2.0,4.62,-7.50,-0.51
276,2022,CAR,1,Sun,September 11,1:00PM ET,L,NaN,0-1,NaN,Cleveland Browns,24.0,26.0,15.0,261.0,207.0,54.0,1.0,23.0,355.0,138.0,217.0,NaN,5.38,-6.82,-1.66
287,2022,SF,1,Sun,September 11,1:00PM ET,L,NaN,0-1,@,Chicago Bears,10.0,19.0,17.0,331.0,155.0,176.0,2.0,15.0,204.0,105.0,99.0,1.0,-11.26,-0.67,0.42
297,2022,SEA,1,Mon,September 12,8:20PM ET,W,NaN,1-0,NaN,Denver Broncos,17.0,16.0,19.0,253.0,177.0,76.0,1.0,20.0,433.0,330.0,103.0,2.0,4.10,-9.94,6.84
307,2022,ARZ,1,Sun,September 11,4:25PM ET,L,NaN,0-1,NaN,Kansas City Chiefs,21.0,44.0,18.0,282.0,179.0,103.0,NaN,33.0,488.0,360.0,128.0,1.0,2.29,-33.41,6.88
318,2022,LAR,1,Thu,September 8,8:20PM ET,L,NaN,0-1,NaN,Buffalo Bills,10.0,31.0,19.0,243.0,191.0,52.0,3.0,23.0,413.0,292.0,121.0,4.0,-10.29,-13.89,3.96
9,2022,MIA,10,Sun,November 13,1:00PM ET,W,NaN,7-3,NaN,Cleveland Browns,39.0,17.0,29.0,491.0,296.0,195.0,NaN,20.0,297.0,185.0,112.0,1.0,28.50,1.04,-4.93

In [18]:
df

,season,team,week,day,date,time,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts
0,2022,MIA,1,Sun,September 11,1:00PM ET,W,NaN,1-0,NaN,New England Patriots,20.0,7.0,18.0,307.0,242.0,65.0,NaN,17.0,271.0,193.0,78.0,3.0,6.08,8.28,1.98
10,2022,BUF,1,Thu,September 8,8:20PM ET,W,NaN,1-0,@,Los Angeles Rams,31.0,10.0,23.0,413.0,292.0,121.0,4.0,19.0,243.0,191.0,52.0,3.0,13.89,10.29,-3.96
20,2022,NE,1,Sun,September 11,1:00PM ET,L,NaN,0-1,@,Miami Dolphins,7.0,20.0,17.0,271.0,193.0,78.0,3.0,18.0,307.0,242.0,65.0,NaN,-8.28,-6.08,-1.98
30,2022,NYJ,1,Sun,September 11,1:00PM ET,L,NaN,0-1,NaN,Baltimore Ravens,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0,-8.07,-3.65,-5.04
40,2022,BAL,1,Sun,September 11,1:00PM ET,W,NaN,1-0,@,New York Jets,24.0,9.0,13.0,274.0,211.0,63.0,1.0,24.0,380.0,297.0,83.0,2.0,3.65,8.07,5.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14796,1994,KC,Wild Card,Sat,December 31,4:00PM ET,L,NaN,9-8,@,Miami Dolphins,17.0,27.0,24.0,414.0,314.0,100.0,2.0,22.0,381.0,249.0,132.0,NaN,8.31,-15.96,-1.16
14943,1994,MIN,Wild Card,Sun,January 1,4:00PM ET,L,NaN,10-7,NaN,Chicago Bears,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0,-9.54,-6.07,0.65
14960,1994,GB,Wild Card,Sat,December 31,12:30PM ET,W,NaN,10-7,NaN,Detroit Lions,16.0,12.0,18.0,336.0,255.0,81.0,NaN,9.0,171.0,175.0,-4.0,NaN,-2.93,11.53,0.69
14978,1994,DET,Wild Card,Sat,December 31,12:30PM ET,L,NaN,9-8,@,Green Bay Packers,12.0,16.0,9.0,171.0,175.0,-4.0,NaN,18.0,336.0,255.0,81.0,NaN,-11.53,2.93,-0.69
14995,1994,CHI,Wild Card,Sun,January 1,4:00PM ET,W,NaN,10-7,@,Minnesota Vikings,35.0,18.0,18.0,308.0,214.0,94.0,2.0,22.0,389.0,340.0,49.0,4.0,6.07,9.54,-0.65

In [19]:
# Team name was abbreviated, making it match to opp name
z = set(df['team'].values.tolist())
y = set(df['opp'].values.tolist())
z = list(z)
z.sort()
y = list(y)
y.sort()

In [20]:
len(y)

32

In [21]:
y

['Arizona Cardinals',
 'Atlanta Falcons',
 'Baltimore Ravens',
 'Buffalo Bills',
 'Carolina Panthers',
 'Chicago Bears',
 'Cincinnati Bengals',
 'Cleveland Browns',
 'Dallas Cowboys',
 'Denver Broncos',
 'Detroit Lions',
 'Green Bay Packers',
 'Houston Texans',
 'Indianapolis Colts',
 'Jacksonville Jaguars',
 'Kansas City Chiefs',
 'Las Vegas Raiders',
 'Los Angeles Chargers',
 'Los Angeles Rams',
 'Miami Dolphins',
 'Minnesota Vikings',
 'New England Patriots',
 'New Orleans Saints',
 'New York Giants',
 'New York Jets',
 'Philadelphia Eagles',
 'Pittsburgh Steelers',
 'San Francisco 49ers',
 'Seattle Seahawks',
 'Tampa Bay Buccaneers',
 'Tennessee Titans',
 'Washington Commanders']

In [22]:
# we must reorder a couple of teams in z so that it matches y
z

['ARZ',
 'ATL',
 'BAL',
 'BUF',
 'CAR',
 'CHI',
 'CIN',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GB',
 'HOU',
 'IND',
 'JAX',
 'KC',
 'LAC',
 'LAR',
 'LV',
 'MIA',
 'MIN',
 'NE',
 'NO',
 'NYG',
 'NYJ',
 'PHI',
 'PIT',
 'SEA',
 'SF',
 'TB',
 'TEN',
 'WAS']

In [23]:
z = z[0:16] + z[18:19] + z[16:17] + z[17:18] + z[19:-5] + z[-4:-3] + z[-5:-4] + z[-3:]
z

['ARZ',
 'ATL',
 'BAL',
 'BUF',
 'CAR',
 'CHI',
 'CIN',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GB',
 'HOU',
 'IND',
 'JAX',
 'KC',
 'LV',
 'LAC',
 'LAR',
 'MIA',
 'MIN',
 'NE',
 'NO',
 'NYG',
 'NYJ',
 'PHI',
 'PIT',
 'SF',
 'SEA',
 'TB',
 'TEN',
 'WAS']

In [24]:
len(set(z))

32

In [25]:
# creating dictionary with the two lists (z & y)
team_dict = dict(zip(z, y))
len(team_dict)

32

In [26]:
# using the manually created team_dictionary to replace the team names.
df = df.replace({"team": team_dict})

In [27]:
df

,season,team,week,day,date,time,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts
0,2022,Miami Dolphins,1,Sun,September 11,1:00PM ET,W,NaN,1-0,NaN,New England Patriots,20.0,7.0,18.0,307.0,242.0,65.0,NaN,17.0,271.0,193.0,78.0,3.0,6.08,8.28,1.98
10,2022,Buffalo Bills,1,Thu,September 8,8:20PM ET,W,NaN,1-0,@,Los Angeles Rams,31.0,10.0,23.0,413.0,292.0,121.0,4.0,19.0,243.0,191.0,52.0,3.0,13.89,10.29,-3.96
20,2022,New England Patriots,1,Sun,September 11,1:00PM ET,L,NaN,0-1,@,Miami Dolphins,7.0,20.0,17.0,271.0,193.0,78.0,3.0,18.0,307.0,242.0,65.0,NaN,-8.28,-6.08,-1.98
30,2022,New York Jets,1,Sun,September 11,1:00PM ET,L,NaN,0-1,NaN,Baltimore Ravens,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0,-8.07,-3.65,-5.04
40,2022,Baltimore Ravens,1,Sun,September 11,1:00PM ET,W,NaN,1-0,@,New York Jets,24.0,9.0,13.0,274.0,211.0,63.0,1.0,24.0,380.0,297.0,83.0,2.0,3.65,8.07,5.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14796,1994,Kansas City Chiefs,Wild Card,Sat,December 31,4:00PM ET,L,NaN,9-8,@,Miami Dolphins,17.0,27.0,24.0,414.0,314.0,100.0,2.0,22.0,381.0,249.0,132.0,NaN,8.31,-15.96,-1.16
14943,1994,Minnesota Vikings,Wild Card,Sun,January 1,4:00PM ET,L,NaN,10-7,NaN,Chicago Bears,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0,-9.54,-6.07,0.65
14960,1994,Green Bay Packers,Wild Card,Sat,December 31,12:30PM ET,W,NaN,10-7,NaN,Detroit Lions,16.0,12.0,18.0,336.0,255.0,81.0,NaN,9.0,171.0,175.0,-4.0,NaN,-2.93,11.53,0.69
14978,1994,Detroit Lions,Wild Card,Sat,December 31,12:30PM ET,L,NaN,9-8,@,Green Bay Packers,12.0,16.0,9.0,171.0,175.0,-4.0,NaN,18.0,336.0,255.0,81.0,NaN,-11.53,2.93,-0.69
14995,1994,Chicago Bears,Wild Card,Sun,January 1,4:00PM ET,W,NaN,10-7,@,Minnesota Vikings,35.0,18.0,18.0,308.0,214.0,94.0,2.0,22.0,389.0,340.0,49.0,4.0,6.07,9.54,-0.65

In [28]:
# create home team and away team columns
h = []
a = [] 
count = 0

afc = ['Baltimore Ravens', 'Buffalo Bills', 'Cincinnati Bengals', 'Cleveland Browns', 'Denver Broncos', 'Houston Texans', 
       'Indianapolis Colts', 'Jacksonville Jaguars', 'Kansas City Chiefs', 'Las Vegas Raiders','Los Angeles Chargers', 
       'Miami Dolphins', 'New England Patriots', 'New York Jets', 'Pittsburgh Steelers', 'Tennessee Titans']

nfc = ['Arizona Cardinals', 'Atlanta Falcons', 'Carolina Panthers', 'Chicago Bears', 'Dallas Cowboys', 'Detroit Lions',
       'Green Bay Packers', 'Los Angeles Rams', 'Minnesota Vikings', 'New Orleans Saints', 'New York Giants',
       'Philadelphia Eagles', 'San Francisco 49ers', 'Seattle Seahawks', 'Tampa Bay Buccaneers', 'Washington Commanders']

for i in df['@']:
    if '@' in str(i):
        h.append(df['opp'].iloc[count])
        a.append(df['team'].iloc[count])
    elif 'N' in str(i): # this entire elif block is to compensate for games in a neutral 'N' stadium specifically for SuperBowls.
        if int(df['season'].iloc[count])%2 == 0:
            if df['team'].iloc[count] in afc:
                h.append(df['team'].iloc[count])
                a.append(df['opp'].iloc[count])
            else: 
                h.append(df['opp'].iloc[count])
                a.append(df['team'].iloc[count])
        else:
            if df['team'].iloc[count] in nfc:
                h.append(df['team'].iloc[count])
                a.append(df['opp'].iloc[count])
            else:
                h.append(df['opp'].iloc[count])
                a.append(df['team'].iloc[count])
    else:
        h.append(df['team'].iloc[count])
        a.append(df['opp'].iloc[count])
    count += 1
        
df = df.assign(away_t = a)
df = df.assign(home_t = h)

### Reduce the number of rows per game from two to one

In [29]:
# we have two rows of data for each game so we will reduce it to one row for each game
df = df.drop_duplicates(subset=['season', 'week', 'home_t', 'away_t'])

In [30]:
# reset index
df = df.reset_index(drop=True)

In [31]:
df = df.sort_values(by=['season', 'week'], ascending=[False, True])
# thinks season and week columns are string datatypes

In [32]:
df

,season,team,week,day,date,time,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts,away_t,home_t
0,2022,Miami Dolphins,1,Sun,September 11,1:00PM ET,W,NaN,1-0,NaN,New England Patriots,20.0,7.0,18.0,307.0,242.0,65.0,NaN,17.0,271.0,193.0,78.0,3.0,6.08,8.28,1.98,New England Patriots,Miami Dolphins
1,2022,Buffalo Bills,1,Thu,September 8,8:20PM ET,W,NaN,1-0,@,Los Angeles Rams,31.0,10.0,23.0,413.0,292.0,121.0,4.0,19.0,243.0,191.0,52.0,3.0,13.89,10.29,-3.96,Buffalo Bills,Los Angeles Rams
2,2022,New York Jets,1,Sun,September 11,1:00PM ET,L,NaN,0-1,NaN,Baltimore Ravens,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0,-8.07,-3.65,-5.04,Baltimore Ravens,New York Jets
3,2022,Cincinnati Bengals,1,Sun,September 11,1:00PM ET,L,OT,0-1,NaN,Pittsburgh Steelers,20.0,23.0,32.0,432.0,299.0,133.0,5.0,13.0,267.0,192.0,75.0,NaN,-7.49,8.41,-4.85,Pittsburgh Steelers,Cincinnati Bengals
4,2022,Cleveland Browns,1,Sun,September 11,1:00PM ET,W,NaN,1-0,@,Carolina Panthers,26.0,24.0,23.0,355.0,138.0,217.0,NaN,15.0,261.0,207.0,54.0,1.0,6.82,-5.38,1.66,Cleveland Browns,Carolina Panthers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7535,1994,Los Angeles Chargers,SuperBowl,Sun,January 29,6:00PM ET,L,NaN,13-6,N,San Francisco 49ers,26.0,49.0,20.0,354.0,287.0,67.0,3.0,28.0,455.0,316.0,139.0,NaN,-3.94,-27.02,4.06,San Francisco 49ers,Los Angeles Chargers
7536,1994,Miami Dolphins,Wild Card,Sat,December 31,4:00PM ET,W,NaN,11-6,NaN,Kansas City Chiefs,27.0,17.0,22.0,381.0,249.0,132.0,NaN,24.0,414.0,314.0,100.0,2.0,15.96,-8.31,1.16,Kansas City Chiefs,Miami Dolphins
7537,1994,New England Patriots,Wild Card,Sun,January 1,12:30PM ET,L,NaN,10-7,@,Cleveland Browns,13.0,20.0,20.0,303.0,246.0,57.0,3.0,22.0,379.0,254.0,125.0,1.0,-11.86,-8.13,10.97,New England Patriots,Cleveland Browns
7538,1994,Minnesota Vikings,Wild Card,Sun,January 1,4:00PM ET,L,NaN,10-7,NaN,Chicago Bears,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0,-9.54,-6.07,0.65,Chicago Bears,Minnesota Vikings
7539,1994,Green Bay Packers,Wild Card,Sat,December 31,12:30PM ET,W,NaN,10-7,NaN,Detroit Lions,16.0,12.0,18.0,336.0,255.0,81.0,NaN,9.0,171.0,175.0,-4.0,NaN,-2.93,11.53,0.69,Detroit Lions,Green Bay Packers

In [33]:
df.tail(30)

,season,team,week,day,date,time,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts,away_t,home_t
7510,1994,Kansas City Chiefs,8,Sun,October 23,1:00PM ET,W,NaN,5-2,NaN,Seattle Seahawks,38.0,23.0,24.0,477.0,305.0,172.0,NaN,16.0,263.0,96.0,167.0,2.0,16.95,-0.26,-1.67,Seattle Seahawks,Kansas City Chiefs
7511,1994,Las Vegas Raiders,8,Sun,October 23,4:00PM ET,W,NaN,3-4,NaN,Atlanta Falcons,30.0,17.0,21.0,313.0,197.0,116.0,1.0,15.0,255.0,185.0,70.0,2.0,1.44,1.86,4.10,Atlanta Falcons,Las Vegas Raiders
7512,1994,Dallas Cowboys,8,Sun,October 23,4:00PM ET,W,NaN,6-1,@,Arizona Cardinals,28.0,21.0,14.0,312.0,237.0,75.0,NaN,22.0,315.0,208.0,107.0,NaN,10.71,-3.98,-3.24,Dallas Cowboys,Arizona Cardinals
7513,1994,Minnesota Vikings,8,Thu,October 20,8:00PM ET,W,OT,5-2,NaN,Green Bay Packers,13.0,10.0,16.0,252.0,230.0,22.0,2.0,12.0,158.0,87.0,71.0,2.0,-22.19,34.26,-3.95,Green Bay Packers,Minnesota Vikings
7514,1994,Detroit Lions,8,Sun,October 23,1:00PM ET,W,NaN,3-4,NaN,Chicago Bears,21.0,16.0,8.0,232.0,49.0,183.0,3.0,22.0,402.0,285.0,117.0,4.0,-17.35,10.02,5.27,Chicago Bears,Detroit Lions
7515,1994,Tampa Bay Buccaneers,8,Sun,October 23,4:00PM ET,L,NaN,2-5,@,San Francisco 49ers,16.0,41.0,17.0,235.0,125.0,110.0,1.0,28.0,451.0,270.0,181.0,1.0,-3.33,-24.24,-1.83,Tampa Bay Buccaneers,San Francisco 49ers
7516,1994,New Orleans Saints,8,Sun,October 23,1:00PM ET,W,NaN,3-5,NaN,Los Angeles Rams,37.0,34.0,18.0,314.0,196.0,118.0,1.0,13.0,242.0,157.0,85.0,3.0,-6.28,13.61,-10.30,Los Angeles Rams,New Orleans Saints
7517,1994,Miami Dolphins,9,Sun,October 30,4:00PM ET,W,NaN,6-2,@,New England Patriots,23.0,3.0,20.0,338.0,198.0,140.0,2.0,11.0,188.0,142.0,46.0,3.0,-5.64,27.59,1.87,Miami Dolphins,New England Patriots
7518,1994,Indianapolis Colts,9,Sun,October 30,4:00PM ET,W,NaN,4-5,NaN,New York Jets,28.0,25.0,22.0,330.0,151.0,179.0,5.0,14.0,256.0,199.0,57.0,1.0,-0.71,14.87,-7.33,New York Jets,Indianapolis Colts
7519,1994,Buffalo Bills,9,Sun,October 30,1:00PM ET,W,NaN,5-3,NaN,Kansas City Chiefs,44.0,10.0,17.0,357.0,180.0,177.0,NaN,16.0,266.0,179.0,87.0,5.0,9.49,23.88,4.11,Kansas City Chiefs,Buffalo Bills
7520,1994,Pittsburgh Steelers,9,Sun,October 30,8:00PM ET,L,OT,5-3,@,Arizona Cardinals,17.0,20.0,12.0,317.0,232.0,85.0,3.0,16.0,335.0,236.0,99.0,1.0,-6.86,-2.29,3.33,Pittsburgh Steelers,Arizona Cardinals
7521,1994,Cleveland Browns,9,Sun,October 30,4:00PM ET,L,NaN,6-2,@,Denver Broncos,14.0,26.0,17.0,317.0,276.0,41.0,1.0,29.0,457.0,343.0,114.0,2.0,-2.40,-6.66,2.08,Cleveland Browns,Denver Broncos
7522,1994,Cincinnati Bengals,9,Sun,October 30,1:00PM ET,L,NaN,0-8,NaN,Dallas Cowboys,20.0,23.0,13.0,320.0,243.0,77.0,1.0,20.0,368.0,272.0,96.0,2.0,0.30,1.58,3.82,Dallas Cowboys,Cincinnati Bengals
7523,1994,Tennessee Titans,9,Sun,October 30,4:00PM ET,L,NaN,1-7,@,Las Vegas Raiders,14.0,17.0,21.0,302.0,203.0,99.0,3.0,16.0,278.0,144.0,134.0,4.0,-5.92,42.91,-20.91,Tennessee Titans,Las Vegas Raiders
7524,1994,Los Angeles Chargers,9,Sun,October 30,4:00PM ET,W,NaN,7-1,NaN,Seattle Seahawks,35.0,15.0,25.0,348.0,187.0,161.0,1.0,14.0,283.0,171.0,112.0,2.0,5.91,15.49,3.99,Seattle Seahawks,Los Angeles Chargers
7525,1994,New York Giants,9,Sun,October 30,1:00PM ET,L,OT,3-5,NaN,Detroit Lions,25.0,28.0,23.0,344.0,149.0,195.0,1.0,24.0,329.0,180.0,149.0,3.0,-0.70,-11.16,4.34,Detroit Lions,New York Giants
7526,1994,Philadelphia Eagles,9,Sun,October 30,1:00PM ET,W,NaN,6-2,@,Washington Commanders,31.0,29.0,19.0,296.0,165.0,131.0,NaN,20.0,349.0,181.0,168.0,3.0,5.55,0.25,-10.57,Philadelphia Eagles,Washington Commanders
7527,1994,Minnesota Vikings,9,Sun,October 30,4:00PM ET,W,NaN,6-2,@,Tampa Bay Buccaneers,36.0,13.0,19.0,361.0,212.0,149.0,2.0,14.0,234.0,185.0,49.0,5.0,5.32,16.03,9.45,Minnesota Vikings,Tampa Bay Buccaneers
7528,1994,Green Bay Packers,9,Mon,October 31,9:00PM ET,W,NaN,4-4,@,Chicago Bears,33.0,6.0,17.0,305.0,82.0,223.0,NaN,12.0,253.0,159.0,94.0,5.0,3.96,25.96,-5.90,Green Bay Packers,Chicago Bears
7529,1994,Pittsburgh Steelers,Conf. Champ.,Sun,January 15,12:30PM ET,L,NaN,13-5,NaN,Los Angeles Chargers,13.0,17.0,22.0,415.0,349.0,66.0,1.0,13.0,226.0,160.0,66.0,1.0,2.66,-0.91,-0.81,Los Angeles Chargers,Pittsburgh Steelers
7530,1994,Dallas Cowboys,Conf. Champ.,Sun,January 15,4:00PM ET,L,NaN,13-5,@,San Francisco 49ers,28.0,38.0,29.0,451.0,352.0,99.0,5.0,19.0,294.0,155.0,139.0,1.0,2.21,-10.92,-4.23,Dallas Cowboys,San Francisco 49ers
7531,1994,Miami Dolphins,Division,Sun,January 8,4:00PM ET,L,NaN,11-7,@,Los Angeles Chargers,21.0,22.0,17.0,282.0,256.0,26.0,NaN,28.0,466.0,264.0,202.0,3.0,9.78,-9.16,-3.54,Miami Dolphins,Los Angeles Chargers
7532,1994,Pittsburgh Steelers,Division,Sat,January 7,12:30PM ET,W,NaN,13-4,NaN,Cleveland Browns,29.0,9.0,23.0,424.0,186.0,238.0,1.0,10.0,186.0,131.0,55.0,2.0,8.48,13.86,-2.06,Cleveland Browns,Pittsburgh Steelers
7533,1994,Dallas Cowboys,Division,Sun,January 8,12:30PM ET,W,NaN,13-4,NaN,Green Bay Packers,35.0,9.0,27.0,450.0,330.0,120.0,2.0,18.0,327.0,228.0,99.0,1.0,11.52,7.11,0.15,Green Bay Packers,Dallas Cowboys
7534,1994,Chicago Bears,Division,Sat,January 7,4:00PM ET,L,NaN,10-8,@,San Francisco 49ers,15.0,44.0,20.0,247.0,208.0,39.0,2.0,27.0,330.0,185.0,145.0,1.0,-7.73,-18.15,1.38,Chicago Bears,San Francisco 49ers
7535,1994,Los Angeles Chargers,SuperBowl,Sun,January 29,6:00PM ET,L,NaN,13-6,N,San Francisco 49ers,26.0,49.0,20.0,354.0,287.0,67.0,3.0,28.0,455.0,316.0,139.0,NaN,-3.94,-27.02,4.06,San Francisco 49ers,Los Angeles Chargers
7536,1994,Miami Dolphins,Wild Card,Sat,December 31,4:00PM ET,W,NaN,11-6,NaN,Kansas City Chiefs,27.0,17.0,22.0,381.0,249.0,132.0,NaN,24.0,414.0,314.0,100.0,2.0,15.96,-8.31,1.16,Kansas City Chiefs,Miami Dolphins
7537,1994,New England Patriots,Wild Card,Sun,January 1,12:30PM ET,L,NaN,10-7,@,Cleveland Browns,13.0,20.0,20.0,303.0,246.0,57.0,3.0,22.0,379.0,254.0,125.0,1.0,-11.86,-8.13,10.97,New England Patriots,Cleveland Browns
7538,1994,Minnesota Vikings,Wild Card,Sun,January 1,4:00PM ET,L,NaN,10-7,NaN,Chicago Bears,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0,-9.54,-6.07,0.65,Chicago Bears,Minnesota Vikings
7539,1994,Green Bay Packers,Wild Card,Sat,December 31,12:30PM ET,W,NaN,10-7,NaN,Detroit Lions,16.0,12.0,18.0,336.0,255.0,81.0,NaN,9.0,171.0,175.0,-4.0,NaN,-2.93,11.53,0.69,Detroit Lions,Green Bay Packers

In [34]:
#df.loc[df['team'] == 'New York Jets'].tail(50)

In [35]:
df[df.week == 'SuperBowl']
# we must determine which teams are the home teams and away teams for the SB. 
# even year = AFC team is the home team for the SB, odd year = NFC team is the home team for the SB
# the game is played on neutral ground where the location (typically a new stadium) is determined years in advance.

,season,team,week,day,date,time,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts,away_t,home_t
442,2021,Cincinnati Bengals,SuperBowl,Sun,February 13,6:30PM ET,L,NaN,13-8,N,Los Angeles Rams,20.0,23.0,15.0,305.0,226.0,79.0,NaN,17.0,313.0,270.0,43.0,2.0,-5.48,-0.42,1.93,Cincinnati Bengals,Los Angeles Rams
711,2020,Kansas City Chiefs,SuperBowl,Sun,February 7,6:30PM ET,L,NaN,16-3,N,Tampa Bay Buccaneers,9.0,31.0,22.0,350.0,243.0,107.0,2.0,26.0,340.0,195.0,145.0,NaN,-7.90,-10.75,-1.18,Tampa Bay Buccaneers,Kansas City Chiefs
980,2019,Kansas City Chiefs,SuperBowl,Sun,February 2,6:30PM ET,W,NaN,15-4,N,San Francisco 49ers,31.0,20.0,26.0,397.0,268.0,129.0,2.0,21.0,351.0,210.0,141.0,2.0,18.54,-5.19,-1.58,Kansas City Chiefs,San Francisco 49ers
1247,2018,New England Patriots,SuperBowl,Sun,February 3,6:30PM ET,W,NaN,14-5,N,Los Angeles Rams,13.0,3.0,22.0,407.0,253.0,154.0,1.0,14.0,260.0,198.0,62.0,1.0,2.46,11.82,-4.34,Los Angeles Rams,New England Patriots
1514,2017,New England Patriots,SuperBowl,Sun,February 4,6:30PM ET,L,NaN,15-4,N,Philadelphia Eagles,33.0,41.0,29.0,613.0,500.0,113.0,1.0,25.0,538.0,374.0,164.0,1.0,27.61,-29.26,-4.65,New England Patriots,Philadelphia Eagles
1781,2016,New England Patriots,SuperBowl,Sun,February 5,6:30PM ET,W,OT,17-2,N,Atlanta Falcons,34.0,28.0,37.0,546.0,442.0,104.0,2.0,17.0,344.0,240.0,104.0,1.0,13.47,-7.42,-1.32,Atlanta Falcons,New England Patriots
2048,2015,Denver Broncos,SuperBowl,Sun,February 7,6:39PM ET,W,NaN,15-4,N,Carolina Panthers,24.0,10.0,11.0,194.0,104.0,90.0,2.0,21.0,315.0,197.0,118.0,4.0,-20.81,20.91,11.64,Denver Broncos,Carolina Panthers
2315,2014,New England Patriots,SuperBowl,Sun,February 1,6:30PM ET,W,NaN,15-4,N,Seattle Seahawks,28.0,24.0,25.0,377.0,320.0,57.0,2.0,20.0,396.0,234.0,162.0,1.0,13.67,-10.40,1.37,Seattle Seahawks,New England Patriots
2582,2013,Denver Broncos,SuperBowl,Sun,February 2,6:32PM ET,L,NaN,15-4,N,Seattle Seahawks,8.0,43.0,18.0,306.0,279.0,27.0,4.0,17.0,341.0,206.0,135.0,NaN,-16.32,-7.18,-9.66,Denver Broncos,Seattle Seahawks
2849,2012,Baltimore Ravens,SuperBowl,Sun,February 3,6:31PM ET,W,NaN,14-6,N,San Francisco 49ers,34.0,31.0,21.0,367.0,274.0,93.0,1.0,23.0,468.0,286.0,182.0,2.0,9.33,-8.82,1.80,San Francisco 49ers,Baltimore Ravens
3116,2011,New England Patriots,SuperBowl,Sun,February 5,6:30PM ET,L,NaN,15-4,N,New York Giants,17.0,21.0,21.0,349.0,266.0,83.0,1.0,26.0,396.0,282.0,114.0,NaN,10.62,-13.35,-1.39,New England Patriots,New York Giants
3383,2010,Pittsburgh Steelers,SuperBowl,Sun,February 6,6:34PM ET,L,NaN,14-5,N,Green Bay Packers,25.0,31.0,19.0,387.0,261.0,126.0,3.0,15.0,338.0,288.0,50.0,NaN,-3.89,-7.72,2.50,Green Bay Packers,Pittsburgh Steelers
3650,2009,Indianapolis Colts,SuperBowl,Sun,February 7,6:31PM ET,L,NaN,16-3,N,New Orleans Saints,17.0,31.0,23.0,432.0,333.0,99.0,1.0,20.0,332.0,281.0,51.0,NaN,5.49,-9.15,-8.49,Indianapolis Colts,New Orleans Saints
3917,2008,Pittsburgh Steelers,SuperBowl,Sun,February 1,6:31PM ET,W,NaN,15-4,N,Arizona Cardinals,27.0,23.0,20.0,292.0,234.0,58.0,1.0,23.0,407.0,374.0,33.0,2.0,4.62,-0.92,1.91,Arizona Cardinals,Pittsburgh Steelers
4184,2007,New England Patriots,SuperBowl,Sun,February 3,6:30PM ET,L,NaN,18-1,N,New York Giants,14.0,17.0,22.0,274.0,229.0,45.0,1.0,17.0,338.0,247.0,91.0,1.0,-2.09,-5.07,-0.70,New England Patriots,New York Giants
4451,2006,Indianapolis Colts,SuperBowl,Sun,February 4,6:27PM ET,W,NaN,16-4,N,Chicago Bears,29.0,17.0,24.0,430.0,239.0,191.0,3.0,11.0,265.0,154.0,111.0,5.0,-3.78,23.57,-10.43,Chicago Bears,Indianapolis Colts
4718,2005,Pittsburgh Steelers,SuperBowl,Sun,February 5,6:27PM ET,W,NaN,15-5,N,Seattle Seahawks,21.0,10.0,14.0,339.0,158.0,181.0,2.0,20.0,396.0,259.0,137.0,1.0,-1.12,5.54,7.56,Pittsburgh Steelers,Seattle Seahawks
4985,2004,New England Patriots,SuperBowl,Sun,February 6,6:38PM ET,W,NaN,17-2,N,Philadelphia Eagles,24.0,21.0,21.0,331.0,219.0,112.0,1.0,24.0,369.0,324.0,45.0,4.0,2.42,-2.04,2.93,Philadelphia Eagles,New England Patriots
5252,2003,New England Patriots,SuperBowl,Sun,February 1,6:25PM ET,W,NaN,17-2,N,Carolina Panthers,32.0,29.0,29.0,481.0,354.0,127.0,1.0,17.0,387.0,295.0,92.0,1.0,17.23,-6.11,-7.78,New England Patriots,Carolina Panthers
5519,2002,Las Vegas Raiders,SuperBowl,Sun,January 26,6:26PM ET,L,NaN,13-6,N,Tampa Bay Buccaneers,21.0,48.0,11.0,269.0,250.0,19.0,5.0,24.0,365.0,215.0,150.0,1.0,-36.42,-4.38,9.42,Tampa Bay Buccaneers,Las Vegas Raiders
5778,2001,New England Patriots,SuperBowl,Sun,February 3,6:40PM ET,W,NaN,14-5,N,Los Angeles Rams,20.0,17.0,15.0,267.0,134.0,133.0,NaN,26.0,427.0,337.0,90.0,3.0,-2.76,2.27,3.96,New England Patriots,Los Angeles Rams
6037,2000,Baltimore Ravens,SuperBowl,Sun,January 28,6:28PM ET,W,NaN,16-4,N,New York Giants,34.0,7.0,13.0,244.0,133.0,111.0,NaN,11.0,152.0,86.0,66.0,5.0,-9.78,34.16,0.70,New York Giants,Baltimore Ravens
6296,1999,Tennessee Titans,SuperBowl,Sun,January 30,6:25PM ET,L,NaN,16-4,N,Los Angeles Rams,16.0,23.0,27.0,367.0,208.0,159.0,NaN,23.0,436.0,407.0,29.0,NaN,13.14,-13.42,-1.52,Tennessee Titans,Los Angeles Rams
6547,1998,Denver Broncos,SuperBowl,Sun,January 31,6:30PM ET,W,NaN,17-2,N,Atlanta Falcons,34.0,19.0,22.0,457.0,336.0,121.0,1.0,21.0,337.0,206.0,131.0,4.0,13.73,14.96,-9.82,Atlanta Falcons,Denver Broncos
6798,1997,Denver Broncos,SuperBowl,Sun,January 25,6:30PM ET,W,NaN,16-4,N,Green Bay Packers,31.0,24.0,21.0,302.0,123.0,179.0,2.0,21.0,350.0,255.0,95.0,3.0,4.51,-3.91,7.71,Denver Broncos,Green Bay Packers
7049,1996,New England Patriots,SuperBowl,Sun,January 26,6:30PM ET,L,NaN,13-6,N,Green Bay Packers,21.0,35.0,16.0,257.0,214.0,43.0,4.0,16.0,323.0,208.0,115.0,NaN,-13.48,2.10,-4.54,Green Bay Packers,New England Patriots
7300,1995,Pittsburgh Steelers,SuperBowl,Sun,January 28,6:33PM ET,L,NaN,13-6,N,Dallas Cowboys,17.0,27.0,25.0,310.0,207.0,103.0,3.0,15.0,254.0,198.0,56.0,NaN,-12.15,-3.32,0.20,Pittsburgh Steelers,Dallas Cowboys
7535,1994,Los Angeles Chargers,SuperBowl,Sun,January 29,6:00PM ET,L,NaN,13-6,N,San Francisco 49ers,26.0,49.0,20.0,354.0,287.0,67.0,3.0,28.0,455.0,316.0,139.0,NaN,-3.94,-27.02,4.06,San Francisco 49ers,Los Angeles Chargers

### Converting Missing Values and Categorical Data Types

In [36]:
df.isnull().sum()

season                  0
team                    0
week                    0
day                     0
date                    0
time                    0
result                  0
ot                   7075
record                  0
@                    3785
opp                     0
points_scored           0
points_allowed          0
1st_downs               0
totyd                   0
passyd                  1
rushyd                  0
to                   1837
1st_downs_allowed       0
totyd_allowed           0
passyd_allowed          1
rushyd_allowed          0
to_forced            1478
off_exp_pts             0
def_exp_pts             0
sts_exp_pts             0
away_t                  0
home_t                  0
dtype: int64

In [37]:
df.dtypes

season                 int64
team                  object
week                  object
day                   object
date                  object
time                  object
result                object
ot                    object
record                object
@                     object
opp                   object
points_scored        float64
points_allowed       float64
1st_downs            float64
totyd                float64
passyd               float64
rushyd               float64
to                   float64
1st_downs_allowed    float64
totyd_allowed        float64
passyd_allowed       float64
rushyd_allowed       float64
to_forced            float64
off_exp_pts          float64
def_exp_pts          float64
sts_exp_pts          float64
away_t                object
home_t                object
dtype: object

In [38]:
# convert NaN values for columns "ot" (overtime), "to" (turnovers), and "to_forced" to the integer 0.
df['ot'] = df['ot'].fillna(0)
df['to'] = df['to'].fillna(0)
df['to_forced'] = df['to_forced'].fillna(0)

In [39]:
# convert misc values for columns "home/away" (home team?) and "ot" (overtime) to a binary integer
df.loc[df["@"] == "@", "@"] = 0
df.loc[df["@"] == "N", "@"] = 0
df.loc[df["ot"] == "OT", "ot"] = 1

In [40]:
# changing the data types for some of the object columns
df[["ot"]] = df[["ot"]].apply(pd.to_numeric)

In [42]:
# convert NaN values for columns "home/away" (home team?) to the integer 1.
df['@'] = df['@'].fillna(1)

In [43]:
# checking how many rows still have missing values in them
df[df.isnull().any(axis=1)]

,season,team,week,day,date,time,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts,away_t,home_t
3516,2009,New York Jets,17,Sun,January 3,8:31PM ET,W,0,9-7,1,Cincinnati Bengals,37.0,0.0,21.0,320.0,63.0,257.0,0.0,5.0,72.0,NaN,72.0,3.0,10.82,33.61,-6.11,Cincinnati Bengals,New York Jets
5125,2003,Las Vegas Raiders,17,Sun,December 28,4:15PM ET,L,0,4-12,0,Los Angeles Chargers,14.0,21.0,9.0,141.0,NaN,141.0,1.0,20.0,337.0,74.0,263.0,0.0,-25.91,-1.64,16.75,Las Vegas Raiders,Los Angeles Chargers

In [44]:
# converting the last four missing values to zero. The net passing yards equaled zero due to sacks.
df['passyd'] = df['passyd'].fillna(0)
df['passyd_allowed'] = df['passyd_allowed'].fillna(0)

In [45]:
# verifying the data types in the df
df.dtypes

season                 int64
team                  object
week                  object
day                   object
date                  object
time                  object
result                object
ot                     int64
record                object
@                      int64
opp                   object
points_scored        float64
points_allowed       float64
1st_downs            float64
totyd                float64
passyd               float64
rushyd               float64
to                   float64
1st_downs_allowed    float64
totyd_allowed        float64
passyd_allowed       float64
rushyd_allowed       float64
to_forced            float64
off_exp_pts          float64
def_exp_pts          float64
sts_exp_pts          float64
away_t                object
home_t                object
dtype: object

In [46]:
# checking how many rows still have missing values in them
len(df[df.isnull().any(axis=1)])

0

### Converting Date and Time columns

In [47]:
# "day" of the week needs to be converted into an integer.
day_dict = {"Tue":1, "Wed":2, "Thu":3, "Fri":4, "Sat":5, "Sun":6, "Mon":7}

# using the manually created day_dictionary to replace the day of the week.
df = df.replace({"day_of_week": day_dict})

In [48]:
df['year'] = df['season']

In [49]:
# date need to be converted into a numerical value (month and day_of_month)
c = []
v = []
for i in df['date']:
    c.append((i.split(' ')[0]))
    v.append(int(i.split(' ')[1]))
df = df.assign(month = c)
df = df.assign(day = v)

In [50]:
# "month of the year needs to be converted into an integer. NFL games start in August (preseason) and end in February (super bowl).
month_dict = {"January":1, "February":2, "March":3, "April":4, "May":5, "June":6, 
            "July":7, "August":8, "September":9, "October":10, "November":11, "December":12}

# using the manually created day_dictionary to replace the day of the week.
df = df.replace({"month": month_dict})

In [51]:
# we can drop the date column after converting it
df = df.drop('date', axis=1)

In [52]:
# time needs to be converted into a numerical value
b = []
for i in df['time']:
    if 'PM' in i:
        b.append(int(i[0]) + 12)
    else:
        b.append(int(i[0]))
df = df.assign(hour = b)

In [53]:
# we can drop the time column after converting it
df = df.drop('time', axis=1)

In [54]:
df['date'] = pd.to_datetime(df[['year', 'month', 'day', 'hour']])

In [55]:
df

,season,team,week,day,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts,away_t,home_t,year,month,hour,date
0,2022,Miami Dolphins,1,11,W,0,1-0,1,New England Patriots,20.0,7.0,18.0,307.0,242.0,65.0,0.0,17.0,271.0,193.0,78.0,3.0,6.08,8.28,1.98,New England Patriots,Miami Dolphins,2022,9,13,2022-09-11 13:00:00
1,2022,Buffalo Bills,1,8,W,0,1-0,0,Los Angeles Rams,31.0,10.0,23.0,413.0,292.0,121.0,4.0,19.0,243.0,191.0,52.0,3.0,13.89,10.29,-3.96,Buffalo Bills,Los Angeles Rams,2022,9,20,2022-09-08 20:00:00
2,2022,New York Jets,1,11,L,0,0-1,1,Baltimore Ravens,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0,-8.07,-3.65,-5.04,Baltimore Ravens,New York Jets,2022,9,13,2022-09-11 13:00:00
3,2022,Cincinnati Bengals,1,11,L,1,0-1,1,Pittsburgh Steelers,20.0,23.0,32.0,432.0,299.0,133.0,5.0,13.0,267.0,192.0,75.0,0.0,-7.49,8.41,-4.85,Pittsburgh Steelers,Cincinnati Bengals,2022,9,13,2022-09-11 13:00:00
4,2022,Cleveland Browns,1,11,W,0,1-0,0,Carolina Panthers,26.0,24.0,23.0,355.0,138.0,217.0,0.0,15.0,261.0,207.0,54.0,1.0,6.82,-5.38,1.66,Cleveland Browns,Carolina Panthers,2022,9,13,2022-09-11 13:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7535,1994,Los Angeles Chargers,SuperBowl,29,L,0,13-6,0,San Francisco 49ers,26.0,49.0,20.0,354.0,287.0,67.0,3.0,28.0,455.0,316.0,139.0,0.0,-3.94,-27.02,4.06,San Francisco 49ers,Los Angeles Chargers,1994,1,18,1994-01-29 18:00:00
7536,1994,Miami Dolphins,Wild Card,31,W,0,11-6,1,Kansas City Chiefs,27.0,17.0,22.0,381.0,249.0,132.0,0.0,24.0,414.0,314.0,100.0,2.0,15.96,-8.31,1.16,Kansas City Chiefs,Miami Dolphins,1994,12,16,1994-12-31 16:00:00
7537,1994,New England Patriots,Wild Card,1,L,0,10-7,0,Cleveland Browns,13.0,20.0,20.0,303.0,246.0,57.0,3.0,22.0,379.0,254.0,125.0,1.0,-11.86,-8.13,10.97,New England Patriots,Cleveland Browns,1994,1,13,1994-01-01 13:00:00
7538,1994,Minnesota Vikings,Wild Card,1,L,0,10-7,1,Chicago Bears,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0,-9.54,-6.07,0.65,Chicago Bears,Minnesota Vikings,1994,1,16,1994-01-01 16:00:00
7539,1994,Green Bay Packers,Wild Card,31,W,0,10-7,1,Detroit Lions,16.0,12.0,18.0,336.0,255.0,81.0,0.0,9.0,171.0,175.0,-4.0,0.0,-2.93,11.53,0.69,Detroit Lions,Green Bay Packers,1994,12,13,1994-12-31 13:00:00

In [56]:
# verifying the data types in the df
df.dtypes

season                        int64
team                         object
week                         object
day                           int64
result                       object
ot                            int64
record                       object
@                             int64
opp                          object
points_scored               float64
points_allowed              float64
1st_downs                   float64
totyd                       float64
passyd                      float64
rushyd                      float64
to                          float64
1st_downs_allowed           float64
totyd_allowed               float64
passyd_allowed              float64
rushyd_allowed              float64
to_forced                   float64
off_exp_pts                 float64
def_exp_pts                 float64
sts_exp_pts                 float64
away_t                       object
home_t                       object
year                          int64
month                         int64
hour                          int64
date                 datetime64[ns]
dtype: object

In [57]:
# we now have to create columns so that it is home_team_pts_scored, home_team_pts_allowed, etc.
ht_pts_scored = []
ht_pts_allowed = [] 
ht_1st_downs = []
ht_1st_downs_allowed = []
ht_totyd = []
ht_passyd = []
ht_rushyd = [] 
ht_to = []
ht_totyd_allowed = []
ht_passyd_allowed = []
ht_rushyd_allowed = []
ht_to_forced = []

counter = 0

for i in df['team']:
    if df['team'].iloc[counter] == df['home_t'].iloc[counter]:
        ht_pts_scored.append(df['points_scored'].iloc[counter])
        ht_pts_allowed.append(df['points_allowed'].iloc[counter])
        ht_1st_downs.append(df['1st_downs'].iloc[counter])
        ht_1st_downs_allowed.append(df['1st_downs_allowed'].iloc[counter])
        ht_totyd.append(df['totyd'].iloc[counter])
        ht_totyd_allowed.append(df['totyd_allowed'].iloc[counter])
        ht_passyd.append(df['passyd'].iloc[counter])
        ht_passyd_allowed.append(df['passyd_allowed'].iloc[counter])
        ht_rushyd.append(df['rushyd'].iloc[counter])
        ht_rushyd_allowed.append(df['rushyd_allowed'].iloc[counter])
        ht_to.append(df['to'].iloc[counter])
        ht_to_forced.append(df['to_forced'].iloc[counter])
    else:
        ht_pts_scored.append(df['points_allowed'].iloc[counter])
        ht_pts_allowed.append(df['points_scored'].iloc[counter])
        ht_1st_downs.append(df['1st_downs_allowed'].iloc[counter])
        ht_1st_downs_allowed.append(df['1st_downs'].iloc[counter])
        ht_totyd.append(df['totyd_allowed'].iloc[counter])
        ht_totyd_allowed.append(df['totyd'].iloc[counter])
        ht_passyd.append(df['passyd_allowed'].iloc[counter])
        ht_passyd_allowed.append(df['passyd'].iloc[counter])
        ht_rushyd.append(df['rushyd_allowed'].iloc[counter])
        ht_rushyd_allowed.append(df['rushyd'].iloc[counter])
        ht_to.append(df['to_forced'].iloc[counter])
        ht_to_forced.append(df['to'].iloc[counter])
    counter += 1

In [58]:
ht_pts_scored[:5]

[20.0, 10.0, 9.0, 20.0, 24.0]

In [59]:
df = df.assign(ht_pts_scored = ht_pts_scored)
df = df.assign(ht_pts_allowed = ht_pts_allowed)
df = df.assign(ht_1st_downs = ht_1st_downs)
df = df.assign(ht_totyd = ht_totyd)
df = df.assign(ht_passyd = ht_passyd)
df = df.assign(ht_rushyd = ht_rushyd)
df = df.assign(ht_to = ht_to)
df = df.assign(ht_1st_downs_allowed = ht_1st_downs_allowed)
df = df.assign(ht_totyd_allowed = ht_totyd_allowed)
df = df.assign(ht_passyd_allowed = ht_passyd_allowed)
df = df.assign(ht_rushyd_allowed = ht_rushyd_allowed)
df = df.assign(ht_to_forced = ht_to_forced)

In [60]:
df

,season,team,week,day,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts,away_t,home_t,year,month,hour,date,ht_pts_scored,ht_pts_allowed,ht_1st_downs,ht_totyd,ht_passyd,ht_rushyd,ht_to,ht_1st_downs_allowed,ht_totyd_allowed,ht_passyd_allowed,ht_rushyd_allowed,ht_to_forced
0,2022,Miami Dolphins,1,11,W,0,1-0,1,New England Patriots,20.0,7.0,18.0,307.0,242.0,65.0,0.0,17.0,271.0,193.0,78.0,3.0,6.08,8.28,1.98,New England Patriots,Miami Dolphins,2022,9,13,2022-09-11 13:00:00,20.0,7.0,18.0,307.0,242.0,65.0,0.0,17.0,271.0,193.0,78.0,3.0
1,2022,Buffalo Bills,1,8,W,0,1-0,0,Los Angeles Rams,31.0,10.0,23.0,413.0,292.0,121.0,4.0,19.0,243.0,191.0,52.0,3.0,13.89,10.29,-3.96,Buffalo Bills,Los Angeles Rams,2022,9,20,2022-09-08 20:00:00,10.0,31.0,19.0,243.0,191.0,52.0,3.0,23.0,413.0,292.0,121.0,4.0
2,2022,New York Jets,1,11,L,0,0-1,1,Baltimore Ravens,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0,-8.07,-3.65,-5.04,Baltimore Ravens,New York Jets,2022,9,13,2022-09-11 13:00:00,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0
3,2022,Cincinnati Bengals,1,11,L,1,0-1,1,Pittsburgh Steelers,20.0,23.0,32.0,432.0,299.0,133.0,5.0,13.0,267.0,192.0,75.0,0.0,-7.49,8.41,-4.85,Pittsburgh Steelers,Cincinnati Bengals,2022,9,13,2022-09-11 13:00:00,20.0,23.0,32.0,432.0,299.0,133.0,5.0,13.0,267.0,192.0,75.0,0.0
4,2022,Cleveland Browns,1,11,W,0,1-0,0,Carolina Panthers,26.0,24.0,23.0,355.0,138.0,217.0,0.0,15.0,261.0,207.0,54.0,1.0,6.82,-5.38,1.66,Cleveland Browns,Carolina Panthers,2022,9,13,2022-09-11 13:00:00,24.0,26.0,15.0,261.0,207.0,54.0,1.0,23.0,355.0,138.0,217.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7535,1994,Los Angeles Chargers,SuperBowl,29,L,0,13-6,0,San Francisco 49ers,26.0,49.0,20.0,354.0,287.0,67.0,3.0,28.0,455.0,316.0,139.0,0.0,-3.94,-27.02,4.06,San Francisco 49ers,Los Angeles Chargers,1994,1,18,1994-01-29 18:00:00,26.0,49.0,20.0,354.0,287.0,67.0,3.0,28.0,455.0,316.0,139.0,0.0
7536,1994,Miami Dolphins,Wild Card,31,W,0,11-6,1,Kansas City Chiefs,27.0,17.0,22.0,381.0,249.0,132.0,0.0,24.0,414.0,314.0,100.0,2.0,15.96,-8.31,1.16,Kansas City Chiefs,Miami Dolphins,1994,12,16,1994-12-31 16:00:00,27.0,17.0,22.0,381.0,249.0,132.0,0.0,24.0,414.0,314.0,100.0,2.0
7537,1994,New England Patriots,Wild Card,1,L,0,10-7,0,Cleveland Browns,13.0,20.0,20.0,303.0,246.0,57.0,3.0,22.0,379.0,254.0,125.0,1.0,-11.86,-8.13,10.97,New England Patriots,Cleveland Browns,1994,1,13,1994-01-01 13:00:00,20.0,13.0,22.0,379.0,254.0,125.0,1.0,20.0,303.0,246.0,57.0,3.0
7538,1994,Minnesota Vikings,Wild Card,1,L,0,10-7,1,Chicago Bears,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0,-9.54,-6.07,0.65,Chicago Bears,Minnesota Vikings,1994,1,16,1994-01-01 16:00:00,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0
7539,1994,Green Bay Packers,Wild Card,31,W,0,10-7,1,Detroit Lions,16.0,12.0,18.0,336.0,255.0,81.0,0.0,9.0,171.0,175.0,-4.0,0.0,-2.93,11.53,0.69,Detroit Lions,Green Bay Packers,1994,12,13,1994-12-31 13:00:00,16.0,12.0,18.0,336.0,255.0,81.0,0.0,9.0,171.0,175.0,-4.0,0.0

In [61]:
# we probably need to develop 'home_team_record' and 'away_team_record' columns, but it might be too difficult to engineer

### Creating the Target feature

In [62]:
# we have to create a target feature 'home_team_wins', where 0 = home team did not win, 1 = home team won
ht_wins = []
counter = 0

for i in df['result']:
    if df['team'].iloc[counter] == df['home_t'].iloc[counter]:
        if i == 'W':
            ht_wins.append(1)
        else:
            ht_wins.append(0)
        counter += 1
    else:
        if i == 'W':
            ht_wins.append(0)
        else:
            ht_wins.append(1)
        counter += 1

In [63]:
df = df.assign(ht_wins = ht_wins)

In [64]:
df

,season,team,week,day,result,ot,record,@,opp,points_scored,points_allowed,1st_downs,totyd,passyd,rushyd,to,1st_downs_allowed,totyd_allowed,passyd_allowed,rushyd_allowed,to_forced,off_exp_pts,def_exp_pts,sts_exp_pts,away_t,home_t,year,month,hour,date,ht_pts_scored,ht_pts_allowed,ht_1st_downs,ht_totyd,ht_passyd,ht_rushyd,ht_to,ht_1st_downs_allowed,ht_totyd_allowed,ht_passyd_allowed,ht_rushyd_allowed,ht_to_forced,ht_wins
0,2022,Miami Dolphins,1,11,W,0,1-0,1,New England Patriots,20.0,7.0,18.0,307.0,242.0,65.0,0.0,17.0,271.0,193.0,78.0,3.0,6.08,8.28,1.98,New England Patriots,Miami Dolphins,2022,9,13,2022-09-11 13:00:00,20.0,7.0,18.0,307.0,242.0,65.0,0.0,17.0,271.0,193.0,78.0,3.0,1
1,2022,Buffalo Bills,1,8,W,0,1-0,0,Los Angeles Rams,31.0,10.0,23.0,413.0,292.0,121.0,4.0,19.0,243.0,191.0,52.0,3.0,13.89,10.29,-3.96,Buffalo Bills,Los Angeles Rams,2022,9,20,2022-09-08 20:00:00,10.0,31.0,19.0,243.0,191.0,52.0,3.0,23.0,413.0,292.0,121.0,4.0,0
2,2022,New York Jets,1,11,L,0,0-1,1,Baltimore Ravens,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0,-8.07,-3.65,-5.04,Baltimore Ravens,New York Jets,2022,9,13,2022-09-11 13:00:00,9.0,24.0,24.0,380.0,297.0,83.0,2.0,13.0,274.0,211.0,63.0,1.0,0
3,2022,Cincinnati Bengals,1,11,L,1,0-1,1,Pittsburgh Steelers,20.0,23.0,32.0,432.0,299.0,133.0,5.0,13.0,267.0,192.0,75.0,0.0,-7.49,8.41,-4.85,Pittsburgh Steelers,Cincinnati Bengals,2022,9,13,2022-09-11 13:00:00,20.0,23.0,32.0,432.0,299.0,133.0,5.0,13.0,267.0,192.0,75.0,0.0,0
4,2022,Cleveland Browns,1,11,W,0,1-0,0,Carolina Panthers,26.0,24.0,23.0,355.0,138.0,217.0,0.0,15.0,261.0,207.0,54.0,1.0,6.82,-5.38,1.66,Cleveland Browns,Carolina Panthers,2022,9,13,2022-09-11 13:00:00,24.0,26.0,15.0,261.0,207.0,54.0,1.0,23.0,355.0,138.0,217.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7535,1994,Los Angeles Chargers,SuperBowl,29,L,0,13-6,0,San Francisco 49ers,26.0,49.0,20.0,354.0,287.0,67.0,3.0,28.0,455.0,316.0,139.0,0.0,-3.94,-27.02,4.06,San Francisco 49ers,Los Angeles Chargers,1994,1,18,1994-01-29 18:00:00,26.0,49.0,20.0,354.0,287.0,67.0,3.0,28.0,455.0,316.0,139.0,0.0,0
7536,1994,Miami Dolphins,Wild Card,31,W,0,11-6,1,Kansas City Chiefs,27.0,17.0,22.0,381.0,249.0,132.0,0.0,24.0,414.0,314.0,100.0,2.0,15.96,-8.31,1.16,Kansas City Chiefs,Miami Dolphins,1994,12,16,1994-12-31 16:00:00,27.0,17.0,22.0,381.0,249.0,132.0,0.0,24.0,414.0,314.0,100.0,2.0,1
7537,1994,New England Patriots,Wild Card,1,L,0,10-7,0,Cleveland Browns,13.0,20.0,20.0,303.0,246.0,57.0,3.0,22.0,379.0,254.0,125.0,1.0,-11.86,-8.13,10.97,New England Patriots,Cleveland Browns,1994,1,13,1994-01-01 13:00:00,20.0,13.0,22.0,379.0,254.0,125.0,1.0,20.0,303.0,246.0,57.0,3.0,1
7538,1994,Minnesota Vikings,Wild Card,1,L,0,10-7,1,Chicago Bears,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0,-9.54,-6.07,0.65,Chicago Bears,Minnesota Vikings,1994,1,16,1994-01-01 16:00:00,18.0,35.0,22.0,389.0,340.0,49.0,4.0,18.0,308.0,214.0,94.0,2.0,0
7539,1994,Green Bay Packers,Wild Card,31,W,0,10-7,1,Detroit Lions,16.0,12.0,18.0,336.0,255.0,81.0,0.0,9.0,171.0,175.0,-4.0,0.0,-2.93,11.53,0.69,Detroit Lions,Green Bay Packers,1994,12,13,1994-12-31 13:00:00,16.0,12.0,18.0,336.0,255.0,81.0,0.0,9.0,171.0,175.0,-4.0,0.0,1

In [65]:
df.dtypes

season                           int64
team                            object
week                            object
day                              int64
result                          object
ot                               int64
record                          object
@                                int64
opp                             object
points_scored                  float64
points_allowed                 float64
1st_downs                      float64
totyd                          float64
passyd                         float64
rushyd                         float64
to                             float64
1st_downs_allowed              float64
totyd_allowed                  float64
passyd_allowed                 float64
rushyd_allowed                 float64
to_forced                      float64
off_exp_pts                    float64
def_exp_pts                    float64
sts_exp_pts                    float64
away_t                          object
home_t                          object
year                             int64
month                            int64
hour                             int64
date                    datetime64[ns]
ht_pts_scored                  float64
ht_pts_allowed                 float64
ht_1st_downs                   float64
ht_totyd                       float64
ht_passyd                      float64
ht_rushyd                      float64
ht_to                          float64
ht_1st_downs_allowed           float64
ht_totyd_allowed               float64
ht_passyd_allowed              float64
ht_rushyd_allowed              float64
ht_to_forced                   float64
ht_wins                          int64
dtype: object

### Dropping unnecessary columns

In [67]:
df = df.drop(['record', 'team', 'result', '@', 'opp', 'points_scored', 'points_allowed', '1st_downs', 
              'totyd', 'passyd', 'rushyd', 'to', '1st_downs_allowed', 'totyd_allowed', 'passyd_allowed', 
              'rushyd_allowed', 'to_forced', 'off_exp_pts', 'def_exp_pts', 'sts_exp_pts', 'year'], axis=1)

In [68]:
df.dtypes

season                           int64
week                            object
day                              int64
ot                               int64
away_t                          object
home_t                          object
month                            int64
hour                             int64
date                    datetime64[ns]
ht_pts_scored                  float64
ht_pts_allowed                 float64
ht_1st_downs                   float64
ht_totyd                       float64
ht_passyd                      float64
ht_rushyd                      float64
ht_to                          float64
ht_1st_downs_allowed           float64
ht_totyd_allowed               float64
ht_passyd_allowed              float64
ht_rushyd_allowed              float64
ht_to_forced                   float64
ht_wins                          int64
dtype: object

### Feature Engineering

In [69]:
# the goal is to obtain a new column that contains rolling_averages for a team over the last four games.
# should the end of a season reset the rolling percentage??? Yes
# creating a df that is organized at the team and season level
grouped_teams = df.groupby("home_t")

In [70]:
# viewing one instance
group_arz = grouped_teams.get_group("Arizona Cardinals")
group_arz

,season,week,day,ot,away_t,home_t,month,hour,date,ht_pts_scored,ht_pts_allowed,ht_1st_downs,ht_totyd,ht_passyd,ht_rushyd,ht_to,ht_1st_downs_allowed,ht_totyd_allowed,ht_passyd_allowed,ht_rushyd_allowed,ht_to_forced,ht_wins
8,2022,1,11,0,Kansas City Chiefs,Arizona Cardinals,9,16,2022-09-11 16:00:00,21.0,44.0,18.0,282.0,179.0,103.0,0.0,33.0,488.0,360.0,128.0,1.0,0
43,2022,11,21,0,San Francisco 49ers,Arizona Cardinals,11,20,2022-11-21 20:00:00,10.0,38.0,19.0,314.0,247.0,67.0,2.0,21.0,387.0,228.0,159.0,0.0,0
75,2022,3,25,0,Los Angeles Rams,Arizona Cardinals,9,16,2022-09-25 16:00:00,12.0,20.0,23.0,365.0,295.0,70.0,0.0,15.0,339.0,239.0,100.0,1.0,0
101,2022,5,9,0,Philadelphia Eagles,Arizona Cardinals,10,16,2022-10-09 16:00:00,17.0,20.0,23.0,363.0,239.0,124.0,1.0,24.0,357.0,218.0,139.0,0.0,0
135,2022,7,20,0,New Orleans Saints,Arizona Cardinals,10,20,2022-10-20 20:00:00,42.0,34.0,21.0,326.0,189.0,137.0,0.0,25.0,494.0,409.0,85.0,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7406,1994,16,18,0,Cincinnati Bengals,Arizona Cardinals,12,16,1994-12-18 16:00:00,28.0,7.0,24.0,364.0,212.0,152.0,0.0,12.0,189.0,125.0,64.0,3.0,1
7439,1994,2,11,0,New York Giants,Arizona Cardinals,9,20,1994-09-11 20:00:00,17.0,20.0,11.0,174.0,135.0,39.0,3.0,19.0,206.0,88.0,118.0,2.0,0
7478,1994,5,2,0,Minnesota Vikings,Arizona Cardinals,10,16,1994-10-02 16:00:00,17.0,7.0,21.0,309.0,200.0,109.0,2.0,19.0,358.0,340.0,18.0,4.0,1
7512,1994,8,23,0,Dallas Cowboys,Arizona Cardinals,10,16,1994-10-23 16:00:00,21.0,28.0,22.0,315.0,208.0,107.0,0.0,14.0,312.0,237.0,75.0,0.0,0
7520,1994,9,30,1,Pittsburgh Steelers,Arizona Cardinals,10,20,1994-10-30 20:00:00,20.0,17.0,16.0,335.0,236.0,99.0,1.0,12.0,317.0,232.0,85.0,3.0,1

In [71]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(4).mean() # closed='left' inside rolling parameters
    # the problem is that it is using the fourth games' info to predict the fourth game and beyond.
    # closed='left' would solve this problem, but that requires datetime. How do I resolve this???
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [72]:
cols = ["ht_wins", "ht_pts_scored", "ht_pts_allowed",
        "ht_totyd", "ht_to", "ht_totyd_allowed", "ht_to_forced",
        "ht_passyd", "ht_rushyd", "ht_passyd_allowed", "ht_rushyd_allowed",
        "ht_1st_downs", "ht_1st_downs_allowed", "ot"]

new_cols = [f"{c}_rolling" for c in cols]

In [73]:
# first four weeks are being dropped because of na values from rolling(4)
# should we bring datetime back??
# testing the function on one group (arz)
rolling_averages(group_arz, cols, new_cols)

,season,week,day,ot,away_t,home_t,month,hour,date,ht_pts_scored,ht_pts_allowed,ht_1st_downs,ht_totyd,ht_passyd,ht_rushyd,ht_to,ht_1st_downs_allowed,ht_totyd_allowed,ht_passyd_allowed,ht_rushyd_allowed,ht_to_forced,ht_wins,ht_wins_rolling,ht_pts_scored_rolling,ht_pts_allowed_rolling,ht_totyd_rolling,ht_to_rolling,ht_totyd_allowed_rolling,ht_to_forced_rolling,ht_passyd_rolling,ht_rushyd_rolling,ht_passyd_allowed_rolling,ht_rushyd_allowed_rolling,ht_1st_downs_rolling,ht_1st_downs_allowed_rolling,ot_rolling
7520,1994,9,30,1,Pittsburgh Steelers,Arizona Cardinals,10,20,1994-10-30 20:00:00,20.0,17.0,16.0,335.0,236.0,99.0,1.0,12.0,317.0,232.0,85.0,3.0,1,0.50,18.75,18.00,283.25,1.50,298.25,2.25,194.75,88.50,224.25,74.00,17.50,16.00,0.25
7357,1994,12,20,0,Philadelphia Eagles,Arizona Cardinals,11,16,1994-11-20 16:00:00,12.0,6.0,16.0,281.0,123.0,158.0,1.0,14.0,185.0,110.0,75.0,2.0,1,0.75,17.50,14.50,310.00,1.00,293.00,2.25,191.75,118.25,229.75,63.25,18.75,14.75,0.25
7370,1994,13,27,1,Chicago Bears,Arizona Cardinals,11,16,1994-11-27 16:00:00,16.0,19.0,15.0,244.0,177.0,67.0,1.0,20.0,318.0,186.0,132.0,2.0,0,0.50,17.25,17.50,293.75,0.75,283.00,1.75,186.00,107.75,191.25,91.75,17.25,15.00,0.50
7398,1994,15,11,0,Washington Commanders,Arizona Cardinals,12,16,1994-12-11 16:00:00,17.0,15.0,14.0,278.0,194.0,84.0,1.0,19.0,406.0,283.0,123.0,2.0,1,0.75,16.25,14.25,284.50,1.00,306.50,2.25,182.50,102.00,202.75,103.75,15.25,16.25,0.50
7406,1994,16,18,0,Cincinnati Bengals,Arizona Cardinals,12,16,1994-12-18 16:00:00,28.0,7.0,24.0,364.0,212.0,152.0,0.0,12.0,189.0,125.0,64.0,3.0,1,0.75,18.25,11.75,291.75,0.75,274.50,2.25,176.50,115.25,176.00,98.50,17.25,16.25,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2022,3,25,0,Los Angeles Rams,Arizona Cardinals,9,16,2022-09-25 16:00:00,12.0,20.0,23.0,365.0,295.0,70.0,0.0,15.0,339.0,239.0,100.0,1.0,0,0.00,18.00,29.00,368.00,0.50,382.25,0.50,265.75,102.25,271.50,110.75,20.75,21.50,0.00
101,2022,5,9,0,Philadelphia Eagles,Arizona Cardinals,10,16,2022-10-09 16:00:00,17.0,20.0,23.0,363.0,239.0,124.0,1.0,24.0,357.0,218.0,139.0,0.0,0,0.00,16.50,26.50,347.00,0.25,382.50,0.50,239.50,107.50,259.25,123.25,21.00,23.00,0.00
135,2022,7,20,0,New Orleans Saints,Arizona Cardinals,10,20,2022-10-20 20:00:00,42.0,34.0,21.0,326.0,189.0,137.0,0.0,25.0,494.0,409.0,85.0,3.0,1,0.25,23.00,29.50,334.00,0.25,419.50,1.25,225.50,108.50,306.50,113.00,21.25,24.25,0.00
163,2022,9,6,0,Seattle Seahawks,Arizona Cardinals,11,16,2022-11-06 16:00:00,21.0,31.0,15.0,262.0,140.0,122.0,1.0,27.0,421.0,263.0,158.0,1.0,0,0.25,23.00,26.25,329.00,0.50,402.75,1.25,215.75,113.25,282.25,120.50,20.50,22.75,0.00
43,2022,11,21,0,San Francisco 49ers,Arizona Cardinals,11,20,2022-11-21 20:00:00,10.0,38.0,19.0,314.0,247.0,67.0,2.0,21.0,387.0,228.0,159.0,0.0,0,0.25,22.50,30.75,316.25,1.00,414.75,1.00,203.75,112.50,279.50,135.25,19.50,24.25,0.00

In [74]:
#apply the new rolling_averages columns to each group
df_rolling = df.groupby(["season", "week"]).apply(lambda x: rolling_averages(x, cols, new_cols))

In [75]:
df_rolling

                  season week  day  ot                away_t  \
season week
1994   1    7313    1994    1    4   0      Seattle Seahawks
            7314    1994    1    4   0   Philadelphia Eagles
            7316    1994    1    4   0     Minnesota Vikings
            7317    1994    1    4   1       Atlanta Falcons
            7318    1994    1    4   0  Tampa Bay Buccaneers
...                  ...  ...  ...  ..                   ...
2022   9    161     2022    9    6   0     Green Bay Packers
            162     2022    9    6   0      Los Angeles Rams
            163     2022    9    6   0      Seattle Seahawks
            156     2022    9    6   1      Tennessee Titans
            154     2022    9    7   0      Baltimore Ravens

                                 home_t  month  hour                date  \
season week
1994   1    7313  Washington Commanders      9    13 1994-09-04 13:00:00
            7314        New York Giants      9    13 1994-09-04 13:00:00
            7316      Green Bay Packers      9    13 1994-09-04 13:00:00
            7317          Detroit Lions      9    13 1994-09-04 13:00:00
            7318          Chicago Bears      9    13 1994-09-04 13:00:00
...                                 ...    ...   ...                 ...
2022   9    161           Detroit Lions     11    13 2022-11-06 13:00:00
            162    Tampa Bay Buccaneers     11    16 2022-11-06 16:00:00
            163       Arizona Cardinals     11    16 2022-11-06 16:00:00
            156      Kansas City Chiefs     11    20 2022-11-06 20:00:00
            154      New Orleans Saints     11    20 2022-11-07 20:00:00

                  ht_pts_scored  ht_pts_allowed  ht_1st_downs  ht_totyd  \
season week
1994   1    7313            7.0            28.0          17.0     258.0
            7314           28.0            23.0          15.0     290.0
            7316           16.0            10.0          15.0     264.0
            7317           31.0            28.0          21.0     352.0
            7318           21.0             9.0          17.0     270.0
...                         ...             ...           ...       ...
2022   9    161            15.0             9.0          19.0     254.0
            162            16.0            13.0          18.0     323.0
            163            21.0            31.0          15.0     262.0
            156            20.0            17.0          29.0     499.0
            154            13.0            27.0          13.0     243.0

                  ht_passyd  ht_rushyd  ht_to  ht_1st_downs_allowed  \
season week
1994   1    7313      224.0       34.0    3.0                  23.0
            7314      149.0      141.0    2.0                  20.0
            7316      170.0       94.0    1.0                  12.0
            7317      203.0      149.0    1.0                  22.0
            7318      204.0       66.0    0.0                  17.0
...                     ...        ...    ...                   ...
2022   9    161       137.0      117.0    1.0                  19.0
            162       272.0       51.0    0.0                   9.0
            163       140.0      122.0    1.0                  27.0
            156       422.0       77.0    1.0                   9.0
            154       195.0       48.0    1.0                  23.0

                  ht_totyd_allowed  ht_passyd_allowed  ht_rushyd_allowed  \
season week
1994   1    7313             360.0              176.0              184.0
            7314             395.0              317.0               78.0
            7316             194.0              146.0               48.0
            7317             389.0              271.0              118.0
            7318             304.0              181.0              123.0
...                            ...                ...                ...
2022   9    161              389.0              283.0              106.0
            162              206.0              138.0               68.0
            163              421.0              263.0              158.0
            156              229.0               57.0              172.0
            154              319.0              131.0              188.0

                  ht_to_forced  ht_wins  ht_wins_rolling  \
season week
1994   1    7313           0.0        0             0.25
            7314           1.0        1             0.25
            7316           3.0        1             0.50
            7317           0.0        1             0.75
            7318           0.0        1             1.00
...                        ...      ...              ...
2022   9    161            3.0        1             0.50
            162            0.0        1             0.50
            163            1.0        0             0.50
            156            0.0        1             0.75
            154            0.0        0             0.50

                  ht_pts_scored_rolling  ht_pts_allowed_rolling  \
season week
1994   1    7313                  22.25                   26.75
            7314                  18.00                   27.25
            7316                  17.00                   22.75
            7317                  20.50                   22.25
            7318                  24.00                   17.50
...                                 ...                     ...
2022   9    161                   19.00                   17.25
            162                   16.25                   15.50
            163                   17.25                   18.25
            156                   18.00                   17.50
            154                   17.50                   22.00

                  ht_totyd_rolling  ht_to_rolling  ht_totyd_allowed_rolling  \
season week
1994   1    7313            306.50           2.75                    362.50
            7314            307.00           2.75                    367.75
            7316            290.25           2.50                    352.25
            7317            291.00           1.75                    334.50
            7318            294.00           1.00                    320.50
...                            ...            ...                       ...
2022   9    161             308.75           1.25                    336.75
            162             288.75           1.00                    308.00
            163             275.50           0.75                    329.25
            156             334.50           0.75                    311.25
            154             331.75           0.75                    293.75

                  ht_to_forced_rolling  ht_passyd_rolling  ht_rushyd_rolling  \
season week
1994   1    7313                  1.25             213.75              92.75
            7314                  0.75             224.50              82.50
            7316                  1.00             213.75              76.50
            7317                  1.00             186.50             104.50
            7318                  1.00             181.50             112.50
...                                ...                ...                ...
2022   9    161                   1.75             153.00             155.75
            162                   1.50             162.25             126.50
            163                   1.25             168.75             106.75
            156                   1.00             242.75              91.75
            154                   0.25             257.25              74.50

                  ht_passyd_allowed_rolling  ht_rushyd_allowed_rolling  \
season week
1994   1    7313                     232.00                     130.50
            7314                     237.50                     130.25
            7316                     236.75                     115.50
            7317                     227.50                     107.00
            7318                     228.75                      91.75
...                                     ...                        ...
2022   9    161                      255.25                      81.50
            162                      227.75                      80.25
            163                      232.25                      97.00
            156                      185.25                     126.00
            154                      147.25                     146.50

                  ht_1st_downs_rolling  ht_1st_downs_allowed_rolling  \
season week
1994   1    7313                 20.25                         23.25
            7314                 19.25                         21.75
            7316                 17.25                         20.75
            7317                 17.00                         19.25
            7318                 17.00                         17.75
...                                ...                           ...
2022   9    161                  19.50                         17.75
            162                  18.50                         16.00
            163                  17.50                         18.00
            156                  20.25                         16.00
            154                  18.75                         17.00

                  ot_rolling
season week
1994   1    7313        0.00
            7314        0.00
            7316        0.00
            7317        0.25
            7318        0.25
...                      ...
2022   9    161         0.00
            162         0.00
            163         0.00
            156         0.25
            154         0.25

[5824 rows x 36 columns]

In [76]:
# dropping extra index levels
df_rolling = df_rolling.droplevel('season')
df_rolling = df_rolling.droplevel('week')
df_rolling

,season,week,day,ot,away_t,home_t,month,hour,date,ht_pts_scored,ht_pts_allowed,ht_1st_downs,ht_totyd,ht_passyd,ht_rushyd,ht_to,ht_1st_downs_allowed,ht_totyd_allowed,ht_passyd_allowed,ht_rushyd_allowed,ht_to_forced,ht_wins,ht_wins_rolling,ht_pts_scored_rolling,ht_pts_allowed_rolling,ht_totyd_rolling,ht_to_rolling,ht_totyd_allowed_rolling,ht_to_forced_rolling,ht_passyd_rolling,ht_rushyd_rolling,ht_passyd_allowed_rolling,ht_rushyd_allowed_rolling,ht_1st_downs_rolling,ht_1st_downs_allowed_rolling,ot_rolling
7313,1994,1,4,0,Seattle Seahawks,Washington Commanders,9,13,1994-09-04 13:00:00,7.0,28.0,17.0,258.0,224.0,34.0,3.0,23.0,360.0,176.0,184.0,0.0,0,0.25,22.25,26.75,306.50,2.75,362.50,1.25,213.75,92.75,232.00,130.50,20.25,23.25,0.00
7314,1994,1,4,0,Philadelphia Eagles,New York Giants,9,13,1994-09-04 13:00:00,28.0,23.0,15.0,290.0,149.0,141.0,2.0,20.0,395.0,317.0,78.0,1.0,1,0.25,18.00,27.25,307.00,2.75,367.75,0.75,224.50,82.50,237.50,130.25,19.25,21.75,0.00
7316,1994,1,4,0,Minnesota Vikings,Green Bay Packers,9,13,1994-09-04 13:00:00,16.0,10.0,15.0,264.0,170.0,94.0,1.0,12.0,194.0,146.0,48.0,3.0,1,0.50,17.00,22.75,290.25,2.50,352.25,1.00,213.75,76.50,236.75,115.50,17.25,20.75,0.00
7317,1994,1,4,1,Atlanta Falcons,Detroit Lions,9,13,1994-09-04 13:00:00,31.0,28.0,21.0,352.0,203.0,149.0,1.0,22.0,389.0,271.0,118.0,0.0,1,0.75,20.50,22.25,291.00,1.75,334.50,1.00,186.50,104.50,227.50,107.00,17.00,19.25,0.25
7318,1994,1,4,0,Tampa Bay Buccaneers,Chicago Bears,9,13,1994-09-04 13:00:00,21.0,9.0,17.0,270.0,204.0,66.0,0.0,17.0,304.0,181.0,123.0,0.0,1,1.00,24.00,17.50,294.00,1.00,320.50,1.00,181.50,112.50,228.75,91.75,17.00,17.75,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,2022,9,6,0,Green Bay Packers,Detroit Lions,11,13,2022-11-06 13:00:00,15.0,9.0,19.0,254.0,137.0,117.0,1.0,19.0,389.0,283.0,106.0,3.0,1,0.50,19.00,17.25,308.75,1.25,336.75,1.75,153.00,155.75,255.25,81.50,19.50,17.75,0.00
162,2022,9,6,0,Los Angeles Rams,Tampa Bay Buccaneers,11,16,2022-11-06 16:00:00,16.0,13.0,18.0,323.0,272.0,51.0,0.0,9.0,206.0,138.0,68.0,0.0,1,0.50,16.25,15.50,288.75,1.00,308.00,1.50,162.25,126.50,227.75,80.25,18.50,16.00,0.00
163,2022,9,6,0,Seattle Seahawks,Arizona Cardinals,11,16,2022-11-06 16:00:00,21.0,31.0,15.0,262.0,140.0,122.0,1.0,27.0,421.0,263.0,158.0,1.0,0,0.50,17.25,18.25,275.50,0.75,329.25,1.25,168.75,106.75,232.25,97.00,17.50,18.00,0.00
156,2022,9,6,1,Tennessee Titans,Kansas City Chiefs,11,20,2022-11-06 20:00:00,20.0,17.0,29.0,499.0,422.0,77.0,1.0,9.0,229.0,57.0,172.0,0.0,1,0.75,18.00,17.50,334.50,0.75,311.25,1.00,242.75,91.75,185.25,126.00,20.25,16.00,0.25
154,2022,9,7,0,Baltimore Ravens,New Orleans Saints,11,20,2022-11-07 20:00:00,13.0,27.0,13.0,243.0,195.0,48.0,1.0,23.0,319.0,131.0,188.0,0.0,0,0.50,17.50,22.00,331.75,0.75,293.75,0.25,257.25,74.50,147.25,146.50,18.75,17.00,0.25